### ISSUE TITLE
Error Account.qime__Sync_w_QB

### ISSUE THREAD

**Issue by simonjasmin** [jawills/QIME#1]
Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') at input location [1,2]
Error is in expression '{!syncQB}' in component <apex:page> in page qime:qbcustomervf: (System Code)

An unexpected error has occurred. Your solution provider has been notified. (System)

**Comment by jawills** [comment]
@simonjasmin I am working on better error messages for self-debugging. In the meantime, can you confirm that you are receiving this error after reauthenticating to QB in the named credential?

**Comment by simonjasmin** [comment]
Hi @jawills ! Thanks for the reply. We just finished the initial configuration. We did reauthenticate to QB in the Named credential. The QIME Salesforce app has an error next to : Authorize with your Quickbooks.

**Comment by jawills** [comment]
@simonjasmin what screen are you referring to? Inside the setup app?

**Comment by simonjasmin** [comment]
> @simonjasmin what screen are you referring to? Inside the setup app?

![QIME-error-authorize-qb](https://github.com/jawills/QIME/assets/17132528/db40e51f-99ec-4144-b011-9491e0772e2f)

**Comment by jawills** [comment]
The error message you are seeing tied with this screen means that your authentication is not configured correctly. I would confirm that all steps were completed for authentication, and that the configuration for the named credential is pointed to the correct instance. You should ensure that:
- qb endpoint is the correct environment (sb/prod)
- realm id is your company's qb id

**Comment by simonjasmin** [comment]
Thanks. I will investigate and get back to you.

**Comment by simonjasmin** [comment]
@jawills We had the incorrect realm ID, but it's working now. Thank you for your support.
